# Generated by Django 2.2.11 on 2020-04-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_geotag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='uuid',
            field=models.TextField(default='<django.db.models.fields.UUIDField>'),
        ),
    ]
