# Generated by Django 2.2.11 on 2020-04-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_geotag', '0002_route_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.TextField(default='<function uuid4 at 0x10a78d2f0>'),
        ),
    ]
