# Generated by Django 2.2.11 on 2020-06-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_geotag', '0004_auto_20200408_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_data',
            field=models.TextField(null=True),
        ),
    ]
